code4romania/whos-who

- src/data/static-pages.js
Closes https://github.com/code4romania/whos-who/issues/13
Added nav items details to config
Manual dev test.
> 13 Adapt main navigation as per design

- src/components/ChartContainer/index.js
- src/components/ChartContainer/styles.scss
- src/components/Home/index.js
- src/components/LineSeparator/index.js
Closes https://github.com/code4romania/whos-who/issues/4
Added flourish chart support with dummy data source. 
CHART_DATA_SOURCE should be updated with real data source.
Please check the deployed preview.
Manual dev testing.
> #4 Add chart container with dummy data source

- src/components/Footer/index.js
Closes #10 
Add a two column footer for the webpage
> Add two columns footer

- src/components/ChartContainer/index.js
Add a new source of data for the Flourish visualization
Visual testing
> Add version 0.1 of the data source

- src/components/Footer/index.js
- remove old two-column links
- add links according to the UX specs
closes #24
> Update the footer

- package-lock.json
- src/data/static-pages.js
- remove all sections except public institutions
- add all the public institutions
Closes #7 
Development on #7 should continue in a different issue, to tackle sharing each accordion.
> Add the right content to the accordions

- src/analyticsTracker.js
Add proper `hostname` and `trackingCode`
> Add proper analytics details

- src/App.js
> Update navbar. Remove 15 recommendations.

- src/components/Home/index.js
> Remove chart (commented).

- src/App.js
- src/components/Home/index.js
Maintain only Code for Romania as developer and remove LineSeparator.
Tested locally.
> Maintain C4R as developer and remove LineSeparator

- src/components/Footer/index.js
- src/components/PrivacyPolicy.js
- src/components/TermsAndConditions.js
> Add policies pages & content

- src/utils/instruments.utils.js
> Add diaspora hub mapping

- public/index.html
> Correct path for the apple-touch-icon

- .github/workflows/deploy.yml
> Initial deployment

- src/data/static-pages.js
> Add institution: ANDPDCA

- public/manifest.json
> Change name and short_name in manifest.json

- public/manifest.json
- src/data/static-pages.js
> Add ANDPDCA

- package-lock.json
- package.json
- src/components/ContentPage/index.js
- src/components/Home/index.js
- src/components/Home/styles.scss
- src/components/SearchResults/index.js
- src/components/SearchResults/styles.scss
- src/data/static-pages.js
- src/utils/instruments.utils.js
Closes https://github.com/code4romania/whos-who/issues/14
- Implement search functionality for accordions
- Manually tested on dev and preview env
> Implement search functionality for accordions

- package-lock.json
- package.json
- src/components/ContentPage/index.js
- src/components/Home/index.js
- src/components/Home/styles.scss
- src/components/SearchResults/index.js
- src/components/SearchResults/styles.scss
- src/data/static-pages.js
- src/utils/instruments.utils.js
Push to production
Tested locally
> Push search and updated static_pages to prod

- package-lock.json
- package.json
- src/App.js
- src/analyticsTracker.js
- src/components/ContentPage/index.js
- src/components/Footer/index.js
- src/components/Form/index.jsx
- src/components/Form/multipleChoice.js
- src/components/Form/singleChoice.js
- src/components/Home/index.js
- src/components/LineSeparator/index.js
- src/components/SearchResults/index.js
- src/utils/instruments.utils.js
> Deploy to prod

- src/data/static-pages.js
added we blinks to official pages in html descriptions 
opened links
> add: hyperlinks to official web pages

- src/data/static-pages.js
Bring in the latest changes from `develop`
> Sync staging & production
